### PR TITLE
Fix issues with light mode in Backup and Pin unlock screens

### LINKED ISSUE #135: light mode issues
- [x] pin edit and lock screen don't support light mode 
- [x] the secret keys are not visible when trying to backup keys

### PR DESCRIPTION
**Pull request by rafaelekol**
Close #135

### CODE REVIEW

File: app/src/main/java/bitcoin/wallet/BaseActivity.kt [hunk 1]
```diff
@@ -24,13 +25,14 @@ abstract class BaseActivity : AppCompatActivity() {
 
     override fun onResume() {
         super.onResume()
+        if (this !is PinActivity) {
```
Comment (abdrasulov) [inline app/src/main/java/bitcoin/wallet/BaseActivity.kt]: It is better to have a flag in `BaseActivity` like `requirePinUnlock`. `PinModule` will start depending also on this flag. This property will be `true` by default. PinActivity will override it to `false`. In this case `BaseActivity` will not know about the `PinActivity`.

Comment (rafaelekol) [reply app/src/main/java/bitcoin/wallet/BaseActivity.kt]: good point
